import { createHash, randomUUID } from "node:crypto";
import { cp, mkdir, readFile, readdir, rename, stat, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import type { AcademyCandidate, RuntimeArtifact } from "./types.js";

interface AcademyIndex { version: 1; candidates: AcademyCandidate[]; }
async function readIndex(root: string): Promise<AcademyIndex> { try { return JSON.parse(await readFile(join(root, "index.json"), "utf8")); } catch (e: any) { if (e?.code === "ENOENT") return { version: 1, candidates: [] }; throw e; } }
async function writeIndex(root: string, index: AcademyIndex) { await mkdir(root, { recursive: true }); const file = join(root, "index.json"), temp = `${file}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(index, null, 2)}\n`); await rename(temp, file); }
async function hashTree(path: string): Promise<string> { const hash = createHash("sha256"); async function visit(current: string) { const info = await stat(current); if (info.isDirectory()) { for (const name of (await readdir(current)).sort()) { hash.update(name); await visit(join(current, name)); } } else hash.update(await readFile(current)); } await visit(path); return hash.digest("hex"); }
export async function searchAcademy(projectRoot: string, userRoot: string | undefined, query = ""): Promise<AcademyCandidate[]> { const tokens = query.toLowerCase().split(/\W+/).filter(Boolean); const scopes: [string, "project" | "user"][] = [[join(projectRoot, ".overpowered", "academy"), "project"], ...(userRoot ? [[userRoot, "user"]] as [string, "user"][] : [])]; const ranked: Array<{ candidate: AcademyCandidate; score: number }> = []; for (const [root, scope] of scopes) { const index = await readIndex(root); for (const candidate of index.candidates) { const haystack = [candidate.name, candidate.description, candidate.capabilityGap, candidate.reuseHypothesis].join(" ").toLowerCase(); const score = (scope === "project" ? 100 : 0) + tokens.reduce((n, token) => n + (haystack.includes(token) ? 10 : 0), 0); if (!tokens.length || score > (scope === "project" ? 100 : 0)) ranked.push({ candidate: { ...candidate, scope }, score }); } } return ranked.sort((a, b) => b.score - a.score || a.candidate.name.localeCompare(b.candidate.name)).slice(0, 10).map(x => x.candidate); }
export async function nominateCandidate(projectRoot: string, artifact: RuntimeArtifact): Promise<AcademyCandidate> { if (!artifact.validation?.ok) throw new Error("Candidate requires successful validation"); if (!artifact.used || !artifact.outcome) throw new Error("Candidate requires actual use and a recorded outcome"); if (artifact.outcome.classification === "ineffective") throw new Error("Ineffective artifacts cannot become candidates"); if (!artifact.outcome.reuseHypothesis?.trim()) throw new Error("Candidate requires a reuse hypothesis"); const root = join(projectRoot, ".overpowered", "academy"); const candidateId = `candidate-${randomUUID()}`; const target = join(root, "candidates", candidateId); const now = new Date().toISOString(); const candidate: AcademyCandidate = { candidateId, status: "CANDIDATE", name: artifact.name, description: artifact.description, artifactType: artifact.type, artifactHash: await hashTree(artifact.sourcePath), capabilityGap: artifact.capabilityGap, originRun: artifact.runId, validation: artifact.validation, outcome: artifact.outcome, limitations: artifact.outcome.limitations, dependencies: artifact.dependencies ?? [], sideEffects: artifact.sideEffects, reuseHypothesis: artifact.outcome.reuseHypothesis.trim(), createdAt: now, scope: "project" }; await mkdir(target, { recursive: true }); await cp(artifact.sourcePath, join(target, "artifact", basename(artifact.sourcePath)), { recursive: true, errorOnExist: true }); await mkdir(join(target, "evidence"), { recursive: true }); await writeFile(join(target, "candidate.json"), `${JSON.stringify(candidate, null, 2)}\n`); const index = await readIndex(root); index.candidates.push(candidate); await writeIndex(root, index); return candidate; }
export async function inspectCandidate(projectRoot: string, candidateId: string): Promise<AcademyCandidate> { const index = await readIndex(join(projectRoot, ".overpowered", "academy")); const candidate = index.candidates.find(x => x.candidateId === candidateId); if (!candidate) throw new Error("Academy candidate not found"); return candidate; }
