import { access, readFile, realpath, stat } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { assertContained, isContained } from "./paths.js";
import type { RuntimeConfig } from "./config.js";
import type { RuntimeArtifact, ToolManifest, ValidationResult } from "./types.js";

const result = (errors: string[], warnings: string[]): ValidationResult => ({ ok: errors.length === 0, checkedAt: new Date().toISOString(), errors, warnings });
export async function validateContext(artifact: RuntimeArtifact): Promise<ValidationResult> { const errors: string[] = [], warnings: string[] = []; const file = join(artifact.sourcePath, "CONTEXT.md"); let text = ""; try { text = await readFile(file, "utf8"); } catch { errors.push("Missing CONTEXT.md"); return result(errors, warnings); } if (!text.trim()) errors.push("Context is empty"); if (/(ignore|override|supersede).{0,40}(system|developer|user|higher.authority)/is.test(text)) errors.push("Context attempts to override higher-authority instructions"); if (/(api.?key|password|secret|token).{0,40}(send|upload|exfiltrate|reveal)/is.test(text)) errors.push("Context contains a possible secret-exfiltration request"); if (text.length > 32_768) errors.push("Context exceeds 32 KiB"); return result(errors, warnings); }
function parseFrontmatter(text: string): Record<string, string> | undefined { const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text); if (!match) return; const out: Record<string, string> = {}; for (const line of match[1].split(/\r?\n/)) { const m = /^([\w-]+):\s*(.+)$/.exec(line); if (m) out[m[1]] = m[2].trim().replace(/^['"]|['"]$/g, ""); } return out; }
export async function validateSkill(artifact: RuntimeArtifact): Promise<ValidationResult> { const errors: string[] = [], warnings: string[] = []; const children = await import("node:fs/promises").then(fs => fs.readdir(artifact.sourcePath, { withFileTypes: true })).catch(() => []); const folders = children.filter(x => x.isDirectory()); const root = folders.length === 1 ? join(artifact.sourcePath, folders[0].name) : artifact.sourcePath; const file = join(root, "SKILL.md"); let text = ""; try { text = await readFile(file, "utf8"); } catch { errors.push("Missing SKILL.md"); return result(errors, warnings); } const fm = parseFrontmatter(text); if (!fm) errors.push("Missing or invalid YAML frontmatter"); else { if (!fm.name) errors.push("Frontmatter name is required"); if (!fm.description) errors.push("Frontmatter description is required"); } if ((await stat(file)).size > 64 * 1024) errors.push("SKILL.md exceeds 64 KiB"); const links = [...text.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)].map(m => m[1]).filter(x => !/^https?:|^#/.test(x)); for (const ref of links) { const target = resolve(dirname(file), ref); if (!isContained(root, target)) errors.push(`Reference escapes skill root: ${ref}`); else try { await access(target); } catch { errors.push(`Broken reference: ${ref}`); } } if (/\b(child_process|exec\(|spawn\(|rm\s+-rf)\b/.test(text)) warnings.push("Skill mentions executable side effects"); return result(errors, warnings); }
export async function readToolManifest(artifact: RuntimeArtifact, config: RuntimeConfig): Promise<ToolManifest> { const raw = JSON.parse(await readFile(join(artifact.sourcePath, "tool.json"), "utf8")); const required = ["name", "description", "runtime", "entrypoint", "inputSchema", "sideEffects", "timeoutMs"]; for (const key of required) if (raw[key] === undefined) throw new Error(`tool.json missing ${key}`); if (!/^[a-z][a-z0-9_]{2,63}$/.test(raw.name)) throw new Error("Invalid tool name"); if (!config.generatedTools.allowedRuntimes.includes(raw.runtime)) throw new Error(`Runtime not allowed: ${raw.runtime}`); if (!raw.inputSchema || raw.inputSchema.type !== "object") throw new Error("inputSchema must be an object JSON schema"); if (!raw.sideEffects || !["none", "workspace", "project", "custom"].includes(raw.sideEffects.filesystemRead) || !["none", "workspace", "project", "custom"].includes(raw.sideEffects.filesystemWrite) || typeof raw.sideEffects.network !== "boolean" || typeof raw.sideEffects.process !== "boolean") throw new Error("Invalid sideEffects declaration"); if (!Number.isInteger(raw.timeoutMs) || raw.timeoutMs < 1 || raw.timeoutMs > config.generatedTools.maxTimeoutMs) throw new Error("Invalid or excessive timeoutMs"); const entrypoint = await assertContained(artifact.sourcePath, resolve(artifact.sourcePath, raw.entrypoint)); if (entrypoint !== await realpath(entrypoint)) throw new Error("Invalid entrypoint"); return raw as ToolManifest; }
export async function validateTool(artifact: RuntimeArtifact, config: RuntimeConfig): Promise<ValidationResult> { const errors: string[] = [], warnings: string[] = []; try { const manifest = await readToolManifest(artifact, config); if (manifest.sideEffects.network || manifest.sideEffects.process || manifest.sideEffects.filesystemWrite === "project" || manifest.sideEffects.filesystemWrite === "custom") warnings.push("Elevated side effects require an explicit human gate"); } catch (e: any) { errors.push(e.message); } return result(errors, warnings); }
export async function validateArtifact(artifact: RuntimeArtifact, config: RuntimeConfig): Promise<ValidationResult> { return artifact.type === "context" ? validateContext(artifact) : artifact.type === "skill" ? validateSkill(artifact) : validateTool(artifact, config); }
