import { randomUUID } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";
import type { RuntimeConfig } from "./config.js";
import { assertContained, assertSafeId } from "./paths.js";
import { StateStore } from "./state.js";
import type { ArtifactType, RuntimeArtifact, RuntimeRun } from "./types.js";

const id = (prefix: string) => `${prefix}-${randomUUID()}`;
export async function createWorkspace(store: StateStore, capabilityGap: string, successTest: string): Promise<RuntimeRun> { if (!capabilityGap.trim() || !successTest.trim()) throw new Error("Capability gap and success test are required"); const now = new Date().toISOString(); const run: RuntimeRun = { runId: id("run"), projectRoot: store.projectRoot, createdAt: now, updatedAt: now, capabilityGap: capabilityGap.trim(), successTest: successTest.trim(), status: "open", artifacts: [] }; const root = join(store.runtimeRoot, run.runId); await mkdir(join(root, "artifacts"), { recursive: true }); await mkdir(join(root, "evidence"), { recursive: true }); await writeFile(join(root, "run.json"), `${JSON.stringify(run, null, 2)}\n`); store.addRun(run); await store.persist(); return run; }
export async function registerArtifact(store: StateStore, config: RuntimeConfig, input: { runId: string; type: ArtifactType; path: string; name: string; description: string }): Promise<RuntimeArtifact> { assertSafeId(input.runId, "runId"); const run = store.snapshot.runs[input.runId]; if (!run || run.status !== "open") throw new Error("Unknown or closed run"); if (run.artifacts.length >= config.runtime.maxArtifactsPerRun) throw new Error(`Artifact budget exceeded (${config.runtime.maxArtifactsPerRun})`); const runRoot = join(store.runtimeRoot, run.runId); const sourcePath = await assertContained(runRoot, resolve(input.path)); const expected = input.type === "context" ? "context" : input.type === "skill" ? "skill" : "tool"; if (basename(sourcePath) !== expected && !sourcePath.split(/[\\/]/).includes(expected)) throw new Error(`Artifact path does not match type ${input.type}`); const now = new Date().toISOString(); const artifact: RuntimeArtifact = { artifactId: id("artifact"), runId: run.runId, type: input.type, name: input.name.trim(), description: input.description.trim(), sourcePath, state: "staged", capabilityGap: run.capabilityGap, successTest: run.successTest, createdAt: now, updatedAt: now }; if (!artifact.name || !artifact.description) throw new Error("Artifact name and description are required"); store.addArtifact(artifact); const metaDir = join(runRoot, "artifacts", artifact.artifactId); await mkdir(metaDir, { recursive: true }); await writeFile(join(metaDir, "artifact.json"), `${JSON.stringify(artifact, null, 2)}\n`); await store.persist(); return artifact; }
export async function cleanupRun(store: StateStore, runId: string): Promise<void> { assertSafeId(runId, "runId"); const run = store.snapshot.runs[runId]; if (!run) throw new Error("Unknown run"); const target = await assertContained(store.runtimeRoot, join(store.runtimeRoot, runId)); await rm(target, { recursive: true, force: false }); for (const artifactId of run.artifacts) { const artifact = store.snapshot.artifacts[artifactId]; if (artifact) store.snapshot.artifacts[artifactId] = { ...artifact, state: "discarded", updatedAt: new Date().toISOString() }; } run.status = "closed"; run.updatedAt = new Date().toISOString(); await store.persist(); }
