import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { nominateCandidate, searchAcademy } from "../../extensions/overpowered-runtime/academy.js";
import type { RuntimeArtifact } from "../../extensions/overpowered-runtime/types.js";
test("Academy nomination requires outcome and creates project candidate", async () => { const root = await mkdtemp(join(tmpdir(), "op-academy-")); const source = join(root, "source"); await mkdir(source); await writeFile(join(source, "CONTEXT.md"), "sample"); const base = { artifactId: "artifact-123456", runId: "run-123456", type: "context", name: "canonical-equipment", description: "Canonical equipment IDs", sourcePath: source, state: "validated", capabilityGap: "normalize equipment identifiers", successTest: "all normalized", createdAt: "", updatedAt: "", validation: { ok: true, checkedAt: "", errors: [], warnings: [] } } as RuntimeArtifact; await assert.rejects(nominateCandidate(root, base), /actual use/); const complete = { ...base, used: true, outcome: { classification: "reusable_signal", observedResult: "passed", evidence: [], limitations: [], reuseHypothesis: "Other equipment imports use the same IDs", recordedAt: "" } } as RuntimeArtifact; const candidate = await nominateCandidate(root, complete); assert.equal(candidate.status, "CANDIDATE"); assert.equal((await searchAcademy(root, undefined, "equipment"))[0].candidateId, candidate.candidateId); });
test("project Academy outranks user Academy", async () => { const project = await mkdtemp(join(tmpdir(), "op-project-")); const user = await mkdtemp(join(tmpdir(), "op-user-")); const mk = async (root: string, id: string, name: string) => { await mkdir(root, { recursive: true }); await writeFile(join(root, "index.json"), JSON.stringify({ version: 1, candidates: [{ candidateId: id, status: "CANDIDATE", name, description: "normalize", artifactType: "context", artifactHash: "x", capabilityGap: "normalize", originRun: "r", validation: { ok: true }, outcome: {}, limitations: [], dependencies: [], reuseHypothesis: "normalize", createdAt: "", scope: "project" }] })); }; await mk(join(project, ".overpowered", "academy"), "project-one", "project"); await mk(user, "user-one", "user"); assert.equal((await searchAcademy(project, user, "normalize"))[0].candidateId, "project-one"); });
